base_url = "https://marceline-cramer.github.io"
compile_sass = true
build_search_index = false
theme = "terminimal"

[markdown]
highlight_code = true

[extra]
author = "Marceline Cramer"
logo_text = "Planet Mars"
